INSERT INTO schedule.room (id, number, type_id) VALUES (1, '521', 1);
INSERT INTO schedule.room (id, number, type_id) VALUES (5, '255', 5);
INSERT INTO schedule.room (id, number, type_id) VALUES (6, '256', 6);
INSERT INTO schedule.room (id, number, type_id) VALUES (7, '240', 7);
INSERT INTO schedule.room (id, number, type_id) VALUES (8, 'м 506', 5);
INSERT INTO schedule.room (id, number, type_id) VALUES (9, 'м 604', 6);
INSERT INTO schedule.room (id, number, type_id) VALUES (10, '517', 5);
INSERT INTO schedule.room (id, number, type_id) VALUES (11, '255-б', 6);
INSERT INTO schedule.room (id, number, type_id) VALUES (14, '248-а', 5);
INSERT INTO schedule.room (id, number, type_id) VALUES (15, '520', 6);
INSERT INTO schedule.room (id, number, type_id) VALUES (16, '255 а', 5);
INSERT INTO schedule.room (id, number, type_id) VALUES (17, '253', 6);
INSERT INTO schedule.room (id, number, type_id) VALUES (20, 'м 505', 5);
INSERT INTO schedule.room (id, number, type_id) VALUES (21, 'м 507', 6);
INSERT INTO schedule.room (id, number, type_id) VALUES (23, '518', 7);
INSERT INTO schedule.room (id, number, type_id) VALUES (25, '519', 6);
INSERT INTO schedule.room (id, number, type_id) VALUES (28, 'м 508', 6);
INSERT INTO schedule.room (id, number, type_id) VALUES (29, '248', 5);
INSERT INTO schedule.room (id, number, type_id) VALUES (30, '249', 6);
INSERT INTO schedule.room (id, number, type_id) VALUES (33, '257', 7);
INSERT INTO schedule.room (id, number, type_id) VALUES (34, '255-а', 5);
INSERT INTO schedule.room (id, number, type_id) VALUES (43, '607', 1);
INSERT INTO schedule.room (id, number, type_id) VALUES (46, '605', 1);
INSERT INTO schedule.room (id, number, type_id) VALUES (49, '250', 7);
INSERT INTO schedule.room (id, number, type_id) VALUES (50, '234', 7);
INSERT INTO schedule.room (id, number, type_id) VALUES (51, '513', 5);
INSERT INTO schedule.room (id, number, type_id) VALUES (52, '522', 6);
INSERT INTO schedule.room (id, number, type_id) VALUES (56, '314', 5);
INSERT INTO schedule.room (id, number, type_id) VALUES (60, 'м 314', 5);
INSERT INTO schedule.room (id, number, type_id) VALUES (73, '338', 5);
INSERT INTO schedule.room (id, number, type_id) VALUES (74, '345', 6);
INSERT INTO schedule.room (id, number, type_id) VALUES (81, '300-а', 5);
INSERT INTO schedule.room (id, number, type_id) VALUES (82, '300-б', 6);
INSERT INTO schedule.room (id, number, type_id) VALUES (85, '334', 5);
INSERT INTO schedule.room (id, number, type_id) VALUES (86, '334’', 6);
INSERT INTO schedule.room (id, number, type_id) VALUES (120, 'м  604', 6);
INSERT INTO schedule.room (id, number, type_id) VALUES (125, '600-г', 5);
INSERT INTO schedule.room (id, number, type_id) VALUES (126, '600-в', 6);
INSERT INTO schedule.room (id, number, type_id) VALUES (130, 'м 608', 6);
INSERT INTO schedule.room (id, number, type_id) VALUES (139, '600-б', 7);
INSERT INTO schedule.room (id, number, type_id) VALUES (213, ' м 608', 6);
INSERT INTO schedule.room (id, number, type_id) VALUES (253, 'м 314/520', 6);