INSERT INTO schedule.lecturer (id, name) VALUES (1166, ' Сакович В.Ю.');
INSERT INTO schedule.lecturer (id, name) VALUES (1103, 'Ананич    Е. А.');
INSERT INTO schedule.lecturer (id, name) VALUES (1091, 'Ананич Е.А.');
INSERT INTO schedule.lecturer (id, name) VALUES (1084, 'Ананич Т.И.');
INSERT INTO schedule.lecturer (id, name) VALUES (1267, 'Ануфрие-ва С.И.');
INSERT INTO schedule.lecturer (id, name) VALUES (1126, 'Базылев Д.Ф.');
INSERT INTO schedule.lecturer (id, name) VALUES (1408, 'Баранов Г.А.');
INSERT INTO schedule.lecturer (id, name) VALUES (1342, 'Барашко Н.В.');
INSERT INTO schedule.lecturer (id, name) VALUES (1129, 'Безверхий А.А.');
INSERT INTO schedule.lecturer (id, name) VALUES (1153, 'Булатов В.И.');
INSERT INTO schedule.lecturer (id, name) VALUES (1213, 'Вальвачев А.Н.');
INSERT INTO schedule.lecturer (id, name) VALUES (1165, 'Варивончик А.О.');
INSERT INTO schedule.lecturer (id, name) VALUES (1195, 'Васьков-ский М.М.');
INSERT INTO schedule.lecturer (id, name) VALUES (1263, 'Васьковский М.М.');
INSERT INTO schedule.lecturer (id, name) VALUES (1323, 'Ведерни-ков С.В.');
INSERT INTO schedule.lecturer (id, name) VALUES (1332, 'Ведерников С.В.');
INSERT INTO schedule.lecturer (id, name) VALUES (1268, 'Видише-ва С.К.');
INSERT INTO schedule.lecturer (id, name) VALUES (1143, 'Видишева С.К.');
INSERT INTO schedule.lecturer (id, name) VALUES (1305, 'Войделе-вич А.С.');
INSERT INTO schedule.lecturer (id, name) VALUES (1250, 'Войделевич А.С.');
INSERT INTO schedule.lecturer (id, name) VALUES (1110, 'Волчкова Г.П.');
INSERT INTO schedule.lecturer (id, name) VALUES (1087, 'Воротницкая Т.И.');
INSERT INTO schedule.lecturer (id, name) VALUES (1207, 'Высоких Л.К.');
INSERT INTO schedule.lecturer (id, name) VALUES (1293, 'Высоких Л.К.            с 04.2017');
INSERT INTO schedule.lecturer (id, name) VALUES (1130, 'Гайдаро-ва О.Т.');
INSERT INTO schedule.lecturer (id, name) VALUES (1150, 'Гайдарова О.Т.');
INSERT INTO schedule.lecturer (id, name) VALUES (1199, 'Голухов В.Г.');
INSERT INTO schedule.lecturer (id, name) VALUES (1138, 'Гончаров Д.А.');
INSERT INTO schedule.lecturer (id, name) VALUES (1098, 'Гусейнова А.С.');
INSERT INTO schedule.lecturer (id, name) VALUES (1282, 'Гутников С Е.');
INSERT INTO schedule.lecturer (id, name) VALUES (1127, 'Деменчук А.К.');
INSERT INTO schedule.lecturer (id, name) VALUES (1187, 'Денисен-ко В.М.');
INSERT INTO schedule.lecturer (id, name) VALUES (1183, 'Денисенко В.М.');
INSERT INTO schedule.lecturer (id, name) VALUES (1123, 'Доцент  Базылев Д.Ф.');
INSERT INTO schedule.lecturer (id, name) VALUES (1146, 'Доцент  Булатов В.И.');
INSERT INTO schedule.lecturer (id, name) VALUES (1211, 'Доцент  Вальвачев А.Н.');
INSERT INTO schedule.lecturer (id, name) VALUES (1260, 'Доцент  Васьковский М.М.');
INSERT INTO schedule.lecturer (id, name) VALUES (1403, 'Доцент  Дубков В.П.');
INSERT INTO schedule.lecturer (id, name) VALUES (1426, 'Доцент  Дугинов О.И.');
INSERT INTO schedule.lecturer (id, name) VALUES (1135, 'Доцент  Кашкевич С.И.');
INSERT INTO schedule.lecturer (id, name) VALUES (1240, 'Доцент  Комраков Б.Б.');
INSERT INTO schedule.lecturer (id, name) VALUES (1279, 'Доцент  Новичкова Д.А.');
INSERT INTO schedule.lecturer (id, name) VALUES (1288, 'Доцент  Орлович Ю.Л.');
INSERT INTO schedule.lecturer (id, name) VALUES (1284, 'Доцент  Размыслович Г.П.');
INSERT INTO schedule.lecturer (id, name) VALUES (1120, 'Доцент Васьковский М.М.');
INSERT INTO schedule.lecturer (id, name) VALUES (1401, 'доцент Новичкова Д.А.');
INSERT INTO schedule.lecturer (id, name) VALUES (1078, 'Доцент Размыслович Г.П.');
INSERT INTO schedule.lecturer (id, name) VALUES (3277, 'ДоцентБазылев Д.Ф.');
INSERT INTO schedule.lecturer (id, name) VALUES (3300, 'ДоцентБулатов В.И.');
INSERT INTO schedule.lecturer (id, name) VALUES (3365, 'ДоцентВальвачев А.Н.');
INSERT INTO schedule.lecturer (id, name) VALUES (3274, 'ДоцентВаськовский М.М.');
INSERT INTO schedule.lecturer (id, name) VALUES (3557, 'ДоцентДубков В.П.');
INSERT INTO schedule.lecturer (id, name) VALUES (3580, 'ДоцентДугинов О.И.');
INSERT INTO schedule.lecturer (id, name) VALUES (3289, 'ДоцентКашкевич С.И.');
INSERT INTO schedule.lecturer (id, name) VALUES (3394, 'ДоцентКомраков Б.Б.');
INSERT INTO schedule.lecturer (id, name) VALUES (3433, 'ДоцентНовичкова Д.А.');
INSERT INTO schedule.lecturer (id, name) VALUES (3442, 'ДоцентОрлович Ю.Л.');
INSERT INTO schedule.lecturer (id, name) VALUES (3232, 'ДоцентРазмыслович Г.П.');
INSERT INTO schedule.lecturer (id, name) VALUES (1362, 'Дубков В.И.');
INSERT INTO schedule.lecturer (id, name) VALUES (1231, 'Дубков В.П.');
INSERT INTO schedule.lecturer (id, name) VALUES (1352, 'Дугинов  О.И.');
INSERT INTO schedule.lecturer (id, name) VALUES (1158, 'Дугинов О.И.');
INSERT INTO schedule.lecturer (id, name) VALUES (1303, 'Жибрик Е.В.');
INSERT INTO schedule.lecturer (id, name) VALUES (1159, 'Жилка А.И.');
INSERT INTO schedule.lecturer (id, name) VALUES (1230, 'Журахов-ский И.В.');
INSERT INTO schedule.lecturer (id, name) VALUES (1145, 'Задворный Я.Б.');
INSERT INTO schedule.lecturer (id, name) VALUES (1364, 'Зенько Т.А.');
INSERT INTO schedule.lecturer (id, name) VALUES (1104, 'Зубович К.А.');
INSERT INTO schedule.lecturer (id, name) VALUES (1101, 'Карпович Н.А.');
INSERT INTO schedule.lecturer (id, name) VALUES (1258, 'Карпович Н.А.  м 508');
INSERT INTO schedule.lecturer (id, name) VALUES (3412, 'Карпович Н.А.  м508');
INSERT INTO schedule.lecturer (id, name) VALUES (1254, 'Карпович Н.А. м508');
INSERT INTO schedule.lecturer (id, name) VALUES (1351, 'Картын-ник Ю.А.');
INSERT INTO schedule.lecturer (id, name) VALUES (1400, 'Картынник Ю.А.');
INSERT INTO schedule.lecturer (id, name) VALUES (1083, 'Кастрица О.А.');
INSERT INTO schedule.lecturer (id, name) VALUES (1137, 'Кашкевич С.И.');
INSERT INTO schedule.lecturer (id, name) VALUES (1157, 'Кибальник Л.А.');
INSERT INTO schedule.lecturer (id, name) VALUES (1086, 'Комаров-ский И.В.');
INSERT INTO schedule.lecturer (id, name) VALUES (1128, 'Конах В.В.');
INSERT INTO schedule.lecturer (id, name) VALUES (1097, 'Кондрать-ева О.М.');
INSERT INTO schedule.lecturer (id, name) VALUES (1088, 'Левчук Е.А.');
INSERT INTO schedule.lecturer (id, name) VALUES (1283, 'Левчук Я.А.');
INSERT INTO schedule.lecturer (id, name) VALUES (1216, 'Ленкевич Е.В.');
INSERT INTO schedule.lecturer (id, name) VALUES (1265, 'Ловеров Я.А.');
INSERT INTO schedule.lecturer (id, name) VALUES (1094, 'Максимо-вич Е.С.');
INSERT INTO schedule.lecturer (id, name) VALUES (1198, 'Матвеев Г.В.');
INSERT INTO schedule.lecturer (id, name) VALUES (1102, 'Мушко В.В.');
INSERT INTO schedule.lecturer (id, name) VALUES (1255, 'Мушко В.В.    м505');
INSERT INTO schedule.lecturer (id, name) VALUES (1107, 'Новичкова Д.А.');
INSERT INTO schedule.lecturer (id, name) VALUES (1208, 'Орешко И.Г.');
INSERT INTO schedule.lecturer (id, name) VALUES (1296, 'Орлович Ю.Л.');
INSERT INTO schedule.lecturer (id, name) VALUES (1105, 'Пазюра         Е. В.');
INSERT INTO schedule.lecturer (id, name) VALUES (1307, 'Пазюра Е.В.');
INSERT INTO schedule.lecturer (id, name) VALUES (1085, 'Петрович С.П.');
INSERT INTO schedule.lecturer (id, name) VALUES (1244, 'Профессор  Мазаник С.А.');
INSERT INTO schedule.lecturer (id, name) VALUES (3398, 'ПрофессорМазаник С.А.');
INSERT INTO schedule.lecturer (id, name) VALUES (1229, 'Радыно Н.Я.');
INSERT INTO schedule.lecturer (id, name) VALUES (1090, 'Размыс-лович Г.П.');
INSERT INTO schedule.lecturer (id, name) VALUES (1082, 'Размысло-вич Г.П.');
INSERT INTO schedule.lecturer (id, name) VALUES (1281, 'Размыслович Г.П.');
INSERT INTO schedule.lecturer (id, name) VALUES (1197, 'Рубашко Н.К.');
INSERT INTO schedule.lecturer (id, name) VALUES (1294, 'Рубашко Н.К. до 04.2017');
INSERT INTO schedule.lecturer (id, name) VALUES (1225, 'Сакович В.Ю.');
INSERT INTO schedule.lecturer (id, name) VALUES (1363, 'Сатоли-на А.В.');
INSERT INTO schedule.lecturer (id, name) VALUES (1371, 'Сатолина А.В.');
INSERT INTO schedule.lecturer (id, name) VALUES (1092, 'Ситникова Т.В.');
INSERT INTO schedule.lecturer (id, name) VALUES (1151, 'Соболев-ская Л.Н.');
INSERT INTO schedule.lecturer (id, name) VALUES (1252, 'Солодов-никова М.Л.');
INSERT INTO schedule.lecturer (id, name) VALUES (1259, 'Солодов-никова М.Л. м 505');
INSERT INTO schedule.lecturer (id, name) VALUES (3413, 'Солодов-никова М.Л. м505');
INSERT INTO schedule.lecturer (id, name) VALUES (1309, 'Солодовни-кова М.Л.');
INSERT INTO schedule.lecturer (id, name) VALUES (1176, 'Ст. преп. Волчкова Г.П.');
INSERT INTO schedule.lecturer (id, name) VALUES (3330, 'Ст. преп.Волчкова Г.П.');
INSERT INTO schedule.lecturer (id, name) VALUES (1318, 'Старший  преподаватель  Гутников С.Е.');
INSERT INTO schedule.lecturer (id, name) VALUES (3472, 'Старший  преподавательГутников С.Е.');
INSERT INTO schedule.lecturer (id, name) VALUES (1298, 'Старший преподаватель  Пазюра Е.В.');
INSERT INTO schedule.lecturer (id, name) VALUES (1220, 'Старший преподаватель Дубков В.П.');
INSERT INTO schedule.lecturer (id, name) VALUES (1172, 'Старший преподаватель Пазюра Е.В.');
INSERT INTO schedule.lecturer (id, name) VALUES (1191, 'Старший преподаватель Рубашко Н.К.');
INSERT INTO schedule.lecturer (id, name) VALUES (3374, 'Старший преподавательДубков В.П.');
INSERT INTO schedule.lecturer (id, name) VALUES (3326, 'Старший преподавательПазюра Е.В.');
INSERT INTO schedule.lecturer (id, name) VALUES (3345, 'Старший преподавательРубашко Н.К.');
INSERT INTO schedule.lecturer (id, name) VALUES (1141, 'Стасеня В.П.');
INSERT INTO schedule.lecturer (id, name) VALUES (1106, 'Филипцов А.В.');
INSERT INTO schedule.lecturer (id, name) VALUES (1228, 'Чернов С.Ю.');
INSERT INTO schedule.lecturer (id, name) VALUES (1093, 'Шевалды-шева Е.З.');
INSERT INTO schedule.lecturer (id, name) VALUES (1111, 'Шевалдышева Е.З.');
INSERT INTO schedule.lecturer (id, name) VALUES (1214, 'Шут О.В.');
INSERT INTO schedule.lecturer (id, name) VALUES (1217, 'Шут.О.В.');