INSERT INTO schedule.subject (id, name) VALUES (1885, '!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!');
INSERT INTO schedule.subject (id, name) VALUES (1877, '!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!');
INSERT INTO schedule.subject (id, name) VALUES (1864, '!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!');
INSERT INTO schedule.subject (id, name) VALUES (1772, 'А и ТЧ');
INSERT INTO schedule.subject (id, name) VALUES (1773, 'А иТЧ');
INSERT INTO schedule.subject (id, name) VALUES (1702, 'Алгебра и теория чисел');
INSERT INTO schedule.subject (id, name) VALUES (1699, 'Англ.  яз.');
INSERT INTO schedule.subject (id, name) VALUES (1503, 'Англ. яз');
INSERT INTO schedule.subject (id, name) VALUES (1860, 'Англ. яз нач. (Ф)');
INSERT INTO schedule.subject (id, name) VALUES (1504, 'Англ. яз.');
INSERT INTO schedule.subject (id, name) VALUES (1798, 'Англ. яз. (Ф)');
INSERT INTO schedule.subject (id, name) VALUES (1605, 'Англ. яз. (ф) до');
INSERT INTO schedule.subject (id, name) VALUES (1876, 'Англ. Яз. Нач. (Ф)');
INSERT INTO schedule.subject (id, name) VALUES (1875, 'Англ. Яз.(ф)');
INSERT INTO schedule.subject (id, name) VALUES (1598, 'Англ.яз');
INSERT INTO schedule.subject (id, name) VALUES (1545, 'Англ.яз.');
INSERT INTO schedule.subject (id, name) VALUES (1602, 'Англ.яз.(ф)');
INSERT INTO schedule.subject (id, name) VALUES (1632, 'Бел. Яз');
INSERT INTO schedule.subject (id, name) VALUES (1635, 'Бел. Яз.');
INSERT INTO schedule.subject (id, name) VALUES (1627, 'Введение в IT (до 18.04)');
INSERT INTO schedule.subject (id, name) VALUES (1629, 'Введение в IT (до18.04)');
INSERT INTO schedule.subject (id, name) VALUES (1491, 'ГА');
INSERT INTO schedule.subject (id, name) VALUES (1587, 'ГА (ф)');
INSERT INTO schedule.subject (id, name) VALUES (1511, 'ГА(ф)');
INSERT INTO schedule.subject (id, name) VALUES (1490, 'Геометрия и алгебра');
INSERT INTO schedule.subject (id, name) VALUES (1592, 'Дискретная математика и Математическая логика');
INSERT INTO schedule.subject (id, name) VALUES (1695, 'ДМ и МЛ');
INSERT INTO schedule.subject (id, name) VALUES (1522, 'ДМиМЛ');
INSERT INTO schedule.subject (id, name) VALUES (1499, 'МА');
INSERT INTO schedule.subject (id, name) VALUES (1676, 'МА (ф)');
INSERT INTO schedule.subject (id, name) VALUES (1512, 'МА(Ф)');
INSERT INTO schedule.subject (id, name) VALUES (1535, 'Математический анализ');
INSERT INTO schedule.subject (id, name) VALUES (1513, 'Прогр.');
INSERT INTO schedule.subject (id, name) VALUES (1693, 'Прогр. (1/2)');
INSERT INTO schedule.subject (id, name) VALUES (1516, 'Прогр.(1/2)');
INSERT INTO schedule.subject (id, name) VALUES (1551, 'Программирование');
INSERT INTO schedule.subject (id, name) VALUES (1588, 'Программирование (1/2)');
INSERT INTO schedule.subject (id, name) VALUES (1837, 'ТГ');
INSERT INTO schedule.subject (id, name) VALUES (1835, 'Теория графов');
INSERT INTO schedule.subject (id, name) VALUES (1492, 'УП');
INSERT INTO schedule.subject (id, name) VALUES (1711, 'УП (Л)');
INSERT INTO schedule.subject (id, name) VALUES (1747, 'Учебная практика');
INSERT INTO schedule.subject (id, name) VALUES (1532, 'Физическая культура');